name: daily-release

on:
  # schedule:
  #   - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: "First Step"
        run: echo "Hello world"