name: Schedule Release

on:
  # schedule:
  #   - cron: '*/5 * * * *'
   workflow_dispatch:


permissions:
  contents: read

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
          - name: Publish Latest Release
            uses: ivangabriele/publish-latest-release@v3
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}