name: Schedule Release

on:
  # schedule:
  #   - cron: '*/5 * * * *'
   workflow_dispatch:


permissions:
  contents: read

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v1
              - name: Jekyll Publish Drafts
                uses: soywiz/github-action-jekyll-publish-drafts@master
                with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  jekyll_path: ./
      # - uses: "marvinpinto/action-automatic-releases@latest"
      #   with:
      #     repo_token: "${{ secrets.GITHUB_TOKEN }}"
      #     automatic_release_tag: "latest"
      #     prerelease: true
      #     title: "Development Build"
      #     files: |
      #       LICENSE.txt
      #       *.jar
      #     run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}